version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/linzhengen/ddd-gin-admin)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
