linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
#    - depguard
#    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
#    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - errcheck
