version: '3'
services:
  ddd-gin-admin:
    image: ddd-gin-admin
    container_name: ddd-gin-admin
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ddd-gin-admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
