---
- name: Dashboard
  icon: dashboard
  router: "/dashboard"
  sequence: 9
- name: DEMO
  icon: tag
  router: "/example/demo"
  sequence: 8
  actions:
    - code: add
      name: Add
      resources:
        - method: POST
          path: "/api/v1/demos"
    - code: edit
      name: Edit
      resources:
        - method: GET
          path: "/api/v1/demos/:id"
        - method: PUT
          path: "/api/v1/demos/:id"
    - code: del
      name: Delete
      resources:
        - method: DELETE
          path: "/api/v1/demos/:id"
    - code: query
      name: Search
      resources:
        - method: GET
          path: "/api/v1/demos"
    - code: disable
      name: Disable
      resources:
        - method: PATCH
          path: "/api/v1/demos/:id/disable"
    - code: enable
      name: Enable
      resources:
        - method: PATCH
          path: "/api/v1/demos/:id/enable"
- name: System Setting
  icon: setting
  sequence: 7
  children:
    - name: Menu
      icon: solution
      router: "/system/menu"
      sequence: 9
      actions:
        - code: add
          name: Add
          resources:
            - method: POST
              path: "/api/v1/menus"
        - code: edit
          name: Edit
          resources:
            - method: GET
              path: "/api/v1/menus/:id"
            - method: PUT
              path: "/api/v1/menus/:id"
        - code: del
          name: Delete
          resources:
            - method: DELETE
              path: "/api/v1/menus/:id"
        - code: query
          name: Search
          resources:
            - method: GET
              path: "/api/v1/menus"
            - method: GET
              path: "/api/v1/menus.tree"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/menus/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/menus/:id/enable"
    - name: Role
      icon: audit
      router: "/system/role"
      sequence: 8
      actions:
        - code: add
          name: Add
          resources:
            - method: GET
              path: "/api/v1/menus.tree"
            - method: POST
              path: "/api/v1/roles"
        - code: edit
          name: Edit
          resources:
            - method: GET
              path: "/api/v1/menus.tree"
            - method: GET
              path: "/api/v1/roles/:id"
            - method: PUT
              path: "/api/v1/roles/:id"
        - code: del
          name: Delete
          resources:
            - method: DELETE
              path: "/api/v1/roles/:id"
        - code: query
          name: Search
          resources:
            - method: GET
              path: "/api/v1/roles"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/roles/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/roles/:id/enable"
    - name: User
      icon: user
      router: "/system/user"
      sequence: 7
      actions:
        - code: add
          name: Add
          resources:
            - method: GET
              path: "/api/v1/roles.select"
            - method: POST
              path: "/api/v1/users"
        - code: edit
          name: Edit
          resources:
            - method: GET
              path: "/api/v1/roles.select"
            - method: GET
              path: "/api/v1/users/:id"
            - method: PUT
              path: "/api/v1/users/:id"
        - code: del
          name: Delete
          resources:
            - method: DELETE
              path: "/api/v1/users/:id"
        - code: query
          name: Search
          resources:
            - method: GET
              path: "/api/v1/users"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/users/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/users/:id/enable"
