// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "tags": [
                    "HealthCheck"
                ],
                "summary": "HealthCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheck"
                        }
                    }
                }
            }
        },
        "/api/v1/menus": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Search menu",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Current page",
                        "name": "current",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search value",
                        "name": "queryValue",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status(1:enable 2:disable)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Show status(1:show 2:hide)",
                        "name": "showStatus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Parent ID",
                        "name": "parentID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.Menu"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IDResult"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/menus.tree": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Search menu tree",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Status(1:enable 2:disable)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Parent ID",
                        "name": "parentID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MenuTree"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/menus/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Get by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Menu"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "404": {
                        "description": "{error:{code:0,message:NotFound}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/menus/{id}/disable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Disable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/menus/{id}/enable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Menu"
                ],
                "summary": "Enable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/current/menutree": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Get user menu tree",
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MenuTree"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/current/password": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Update password",
                "parameters": [
                    {
                        "description": "Request parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdatePasswordParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/current/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UserLoginInfo"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/login": {
            "post": {
                "tags": [
                    "Login"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Request parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginTokenInfo"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/login/captcha": {
            "get": {
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Response captcha",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Captcha ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reload",
                        "name": "reload",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ResCaptcha"
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/login/captchaid": {
            "get": {
                "tags": [
                    "Login"
                ],
                "summary": "Get Captcha",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginCaptcha"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/login/exit": {
            "post": {
                "tags": [
                    "Login"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    }
                }
            }
        },
        "/api/v1/pub/refresh-token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.LoginTokenInfo"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Search role",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Current page",
                        "name": "current",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search value",
                        "name": "queryValue",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status(1:enable 2:disable)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.Role"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IDResult"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles.select": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Search selected data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search value",
                        "name": "queryValue",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status(1:enable 2:disable)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.Role"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:未知的查询类型}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Role"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "404": {
                        "description": "{error:{code:0,message:NotFound}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Role"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{id}/disable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Disable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/roles/{id}/enable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Enable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Search user",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Current page",
                        "name": "current",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search value",
                        "name": "queryValue",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Role IDs(Comma division)",
                        "name": "roleIDs",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status (1: Enabled 2: Disabled)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ListResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "list": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.UserShow"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "Create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IDResult"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.User"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "404": {
                        "description": "{error:{code:0,message:NotFound}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.User"
                        }
                    },
                    "400": {
                        "description": "{error:{code:0,message:BadRequest}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/disable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Disable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/enable": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Enable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{status:OK}",
                        "schema": {
                            "$ref": "#/definitions/response.StatusResult"
                        }
                    },
                    "401": {
                        "description": "{error:{code:0,message:Unauthorized}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    },
                    "500": {
                        "description": "{error:{code:0,message:SystemError}}",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pagination.Pagination": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "Current Page",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "Page Size",
                    "type": "integer"
                },
                "total": {
                    "description": "Total count",
                    "type": "integer"
                }
            }
        },
        "request.LoginParam": {
            "type": "object",
            "required": [
                "captcha_code",
                "captcha_id",
                "password",
                "user_name"
            ],
            "properties": {
                "captcha_code": {
                    "description": "Captcha Code",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "Captcha ID",
                    "type": "string"
                },
                "password": {
                    "description": "Password(md5)",
                    "type": "string"
                },
                "user_name": {
                    "description": "User Name",
                    "type": "string"
                }
            }
        },
        "request.Menu": {
            "type": "object",
            "required": [
                "name",
                "show_status",
                "status"
            ],
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "icon": {
                    "description": "Icon",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "memo": {
                    "description": "Memo",
                    "type": "string"
                },
                "name": {
                    "description": "Name",
                    "type": "string"
                },
                "parent_id": {
                    "description": "Parent ID",
                    "type": "string"
                },
                "parent_path": {
                    "description": "Parent Path",
                    "type": "string"
                },
                "router": {
                    "description": "Router",
                    "type": "string"
                },
                "sequence": {
                    "description": "Sequence",
                    "type": "integer"
                },
                "show_status": {
                    "description": "Show Status(1:show 2:hide)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "status": {
                    "description": "Menu Status(1:enable 2:disable)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "updated_at": {
                    "description": "UpdatedAt",
                    "type": "string"
                }
            }
        },
        "request.Role": {
            "type": "object",
            "required": [
                "name",
                "status"
            ],
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "memo": {
                    "description": "Memo",
                    "type": "string"
                },
                "name": {
                    "description": "Name",
                    "type": "string"
                },
                "sequence": {
                    "description": "Sequence",
                    "type": "integer"
                },
                "status": {
                    "description": "Status(1:enable 2:disable)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "updated_at": {
                    "description": "UpdatedAt",
                    "type": "string"
                }
            }
        },
        "request.UpdatePasswordParam": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "New Password",
                    "type": "string"
                },
                "old_password": {
                    "description": "Old Password",
                    "type": "string"
                }
            }
        },
        "request.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "email": {
                    "description": "Email",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "password": {
                    "description": "Password",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone",
                    "type": "string"
                },
                "real_name": {
                    "description": "Real Name",
                    "type": "string"
                },
                "role_ids": {
                    "description": "RoleIDs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "Status(1:enable 2:disable)",
                    "type": "integer"
                },
                "user_name": {
                    "description": "User Name",
                    "type": "string"
                }
            }
        },
        "response.ErrorItem": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error Code",
                    "type": "integer"
                },
                "message": {
                    "description": "Error Message",
                    "type": "string"
                }
            }
        },
        "response.ErrorResult": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ErrorItem"
                        }
                    ]
                }
            }
        },
        "response.HealthCheck": {
            "type": "object",
            "properties": {
                "checked_at": {
                    "description": "CheckedAt",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "string"
                }
            }
        },
        "response.IDResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "response.ListResult": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "List"
                },
                "pagination": {
                    "description": "Pagination",
                    "allOf": [
                        {
                            "$ref": "#/definitions/pagination.Pagination"
                        }
                    ]
                }
            }
        },
        "response.LoginCaptcha": {
            "type": "object",
            "properties": {
                "captcha_id": {
                    "description": "Captcha ID",
                    "type": "string"
                }
            }
        },
        "response.LoginTokenInfo": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Access Token",
                    "type": "string"
                },
                "expires_at": {
                    "description": "Expires At",
                    "type": "integer"
                },
                "token_type": {
                    "description": "Token Type",
                    "type": "string"
                }
            }
        },
        "response.Menu": {
            "type": "object",
            "required": [
                "name",
                "show_status",
                "status"
            ],
            "properties": {
                "actions": {
                    "description": "Actions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MenuAction"
                    }
                },
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "icon": {
                    "description": "Icon",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "memo": {
                    "description": "Memo",
                    "type": "string"
                },
                "name": {
                    "description": "Name",
                    "type": "string"
                },
                "parent_id": {
                    "description": "Parent ID",
                    "type": "string"
                },
                "parent_path": {
                    "description": "Parent Path",
                    "type": "string"
                },
                "router": {
                    "description": "Router",
                    "type": "string"
                },
                "sequence": {
                    "description": "Sequence",
                    "type": "integer"
                },
                "show_status": {
                    "description": "Show Status(1:show 2:hide)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "status": {
                    "description": "Menu Status(1:enable 2:disable)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "updated_at": {
                    "description": "UpdatedAt",
                    "type": "string"
                }
            }
        },
        "response.MenuAction": {
            "type": "object",
            "required": [
                "code",
                "menu_id",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "menu_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MenuActionResource"
                    }
                }
            }
        },
        "response.MenuActionResource": {
            "type": "object",
            "required": [
                "method",
                "path"
            ],
            "properties": {
                "action_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "response.MenuTree": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MenuAction"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MenuTree"
                    }
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "parent_path": {
                    "type": "string"
                },
                "router": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "show_status": {
                    "description": "1:show 2:hide",
                    "type": "integer"
                },
                "status": {
                    "description": "1:enable 2:disable",
                    "type": "integer"
                }
            }
        },
        "response.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "memo": {
                    "description": "Memo",
                    "type": "string"
                },
                "name": {
                    "description": "Name",
                    "type": "string"
                },
                "role_menus": {
                    "description": "RoleMenus",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RoleMenu"
                    }
                },
                "sequence": {
                    "description": "Sequence",
                    "type": "integer"
                },
                "status": {
                    "description": "Status(1:enable 2:disable)",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "UpdatedAt",
                    "type": "string"
                }
            }
        },
        "response.RoleMenu": {
            "type": "object",
            "required": [
                "action_id",
                "menu_id",
                "role_id"
            ],
            "properties": {
                "action_id": {
                    "description": "Action ID",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "menu_id": {
                    "description": "Menu ID",
                    "type": "string"
                },
                "role_id": {
                    "description": "Role ID",
                    "type": "string"
                }
            }
        },
        "response.StatusResult": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Result status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.StatusText"
                        }
                    ]
                }
            }
        },
        "response.StatusText": {
            "type": "string",
            "enum": [
                "OK",
                "ERROR",
                "FAIL"
            ],
            "x-enum-varnames": [
                "OKStatus",
                "ErrorStatus",
                "FailStatus"
            ]
        },
        "response.User": {
            "type": "object",
            "required": [
                "real_name",
                "status",
                "user_name",
                "user_roles"
            ],
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "creator": {
                    "description": "Creator",
                    "type": "string"
                },
                "email": {
                    "description": "Email",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "password": {
                    "description": "Password",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone",
                    "type": "string"
                },
                "real_name": {
                    "description": "Real Name",
                    "type": "string"
                },
                "status": {
                    "description": "Status(1:enable 2:disable)",
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                },
                "user_name": {
                    "description": "User Name",
                    "type": "string"
                },
                "user_roles": {
                    "description": "UserRoles",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.UserRole"
                    }
                }
            }
        },
        "response.UserLoginInfo": {
            "type": "object",
            "properties": {
                "real_name": {
                    "description": "Real Name",
                    "type": "string"
                },
                "roles": {
                    "description": "Role",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Role"
                    }
                },
                "user_id": {
                    "description": "User ID",
                    "type": "string"
                },
                "user_name": {
                    "description": "User Name",
                    "type": "string"
                }
            }
        },
        "response.UserRole": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "role_id": {
                    "description": "Role ID",
                    "type": "string"
                },
                "user_id": {
                    "description": "User ID",
                    "type": "string"
                }
            }
        },
        "response.UserShow": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt",
                    "type": "string"
                },
                "email": {
                    "description": "Email",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone",
                    "type": "string"
                },
                "real_name": {
                    "description": "Real Name",
                    "type": "string"
                },
                "roles": {
                    "description": "Roles",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Role"
                    }
                },
                "status": {
                    "description": "Status(1:enable 2:disable)",
                    "type": "integer"
                },
                "user_name": {
                    "description": "User Name",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ddd-gin-admin",
	Description:      "RBAC scaffolding based on DDD + GIN + GORM + CASBIN + WIRE.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
